---
labels:
  platform: windows/amd64
  backend: docker

# variables:
#   - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
#   - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
#   - &publish_platforms 'linux/arm64,linux/amd64'

when:
  - event: push
    branch: "flimmy_ci_tests"

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v1
    pull: false
    settings:
      path: "$CI_WORKSPACE/src"

steps:
  - name: get craftmaker
    image: opencloudeu/woodpecker-windows-git:v1
    commands:
      - bash -c pwd
      - bash -c "ls -l /c/woodpecker"
      - bash -c "ls -l /c/woodpecker/src"
      - bash -c "ls -l /c/woodpecker/src/github.com"

  - name: ls
    image: opencloudeu/woodpecker-windows-python:v1
    commands:
      - "echo in $(pwd)"
      - "ls -l /"
