---
labels:
  platform: windows/amd64
  backend: docker

# variables:
#   - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
#   - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
#   - &publish_platforms 'linux/arm64,linux/amd64'

when:
  - event: push
    branch: "flimmy_ci_tests"

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v1

steps:
  - name: Clone Craftmaster
    image: opencloudeu/woodpecker-windows-git:v1
    commands:
      - bash -c "git clone --depth=1 https://invent.kde.org/kde/craftmaster.git `$$CI_WORKSPACE/woodpecker_craft/CraftMaster/CraftMaster"

  - name: Craft setup
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - New-Item -Path $$HOME/cache -ItemType Directory -ErrorAction SilentlyContinue
      - .github/workflows/.craft.ps1 --setup

  - name: Craft unshelve
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --unshelve .craft.shelf
      # bootsrtap in case the shelf was empty
      - .github/workflows/.craft.ps1 -c craft

  - name: Craft Prepare
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --set "forceAsserts$$($$env:CI_PIPELINE_EVENT -ne "tag")" opencloud/opencloud-desktop
      - .github/workflows/.craft.ps1 -c --set "srcDir=$$env:CI_WORKSPACE" opencloud/opencloud-desktop
      - .github/workflows/.craft.ps1 -c --set "buildNumber=$$env:CI_PIPELINE_NUMBER" opencloud/opencloud-desktop
      - .github/workflows/.craft.ps1 -c dev-utils/nsis

  - name: Install dependencies
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --install-deps opencloud/opencloud-desktop

  - name: Update Shelf
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --shelve .craft.shelf
      - Copy-Item .craft.shelf binaries/craft.shelf

  - name: Build
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --no-cache opencloud/opencloud-desktop

  - name: Run tests
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --no-cache --test opencloud/opencloud-desktop

  - name: Package
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --no-cache --package opencloud/opencloud-desktop

  - name: Package Appx
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - .github/workflows/.craft.ps1 -c --no-cache --package --options "[Packager]PackageType=AppxPackager" --options "[Packager]Destination=$$env:CI_WORKSPACE/appx/" opencloud/opencloud-desktop

  - name: show artifacts
    image: opencloudeu/woodpecker-windows-python:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
    commands:
      - Copy-Item ${HOME}/craft/binaries/* binaries/
      - Copy-Item appx/* binaries/
      - dir binaries


  # - name: ls
  #   image: opencloudeu/woodpecker-windows-python:v1
  #   environment:
  #     CRAFT_TARGET: windows-cl-msvc2022-x86_64
  #     CRAFT_PACKAGE_SYMBOLS: true
  #   entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$IsWindows=$true; New-Item -itemtype SymbolicLink -path $HOME/craft -value $env:CI_WORKSPACE/woodpecker_craft; echo $([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT))) | iex"]
  #   commands:
  #     - New-Item -itemtype SymbolicLink -path $$HOME/craft -value $$env:CI_WORKSPACE/woodpecker_craft
  #     - dir $$HOME
  #     - New-Item -Path $$HOME/cache -ItemType Directory -ErrorAction SilentlyContinue
  #     - dir $$HOME
  #     - .github/workflows/.craft.ps1 --setup
  #     - .github/workflows/.craft.ps1 -c --unshelve .craft.shelf
  #     - .github/workflows/.craft.ps1 -c craft
  #     - New-Item -ItemType Directory binaries
  #     - .github/workflows/.craft.ps1 -c --set "forceAsserts$$($$env:CI_PIPELINE_EVENT -ne "tag")" opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c --set "srcDir=$$env:CI_WORKSPACE" opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c --set "buildNumber=$$env:CI_PIPELINE_NUMBER" opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c dev-utils/nsis
  #     - .github/workflows/.craft.ps1 -c --install-deps opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c --shelve .craft.shelf
  #     - Copy-Item .craft.shelf binaries/craft.shelf
  #     - .github/workflows/.craft.ps1 -c --no-cache opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c --no-cache --test opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c --no-cache --package opencloud/opencloud-desktop
  #     - .github/workflows/.craft.ps1 -c --no-cache --package --options "[Packager]PackageType=AppxPackager" --options "[Packager]Destination=$$env:CI_WORKSPACE/appx/" opencloud/opencloud-desktop
  #     - Copy-Item ${HOME}/craft/binaries/* binaries/
  #     - Copy-Item appx/* binaries/
  #     - dir binaries
      