---
labels:
  platform: windows/amd64
  backend: docker

# variables:
#   - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
#   - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
#   - &publish_platforms 'linux/arm64,linux/amd64'

when:
  - event: push
    branch: "flimmy_ci_tests"

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v1

steps:
  - name: get craftmaker
    image: opencloudeu/woodpecker-windows-git:v1
    commands:
      - bash -c "git clone --depth=1 https://invent.kde.org/kde/craftmaster.git $$env:CI_WORKSPACE/woodpecker_craft/CraftMaster/CraftMaster"

  - name: ls
    image: opencloudeu/woodpecker-windows-python:v1
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$$IsWindows=$$true; [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT)) | iex"]
    commands:
      - New-Item -itemtype SymbolicLink -path $$HOME/craft -value $$env:CI_WORKSPACE/woodpecker_craft
      - .github/workflows/.craft.ps1 --setup
