---
labels:
  platform: windows/amd64
  backend: docker

# variables:
#   - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
#   - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
#   - &publish_platforms 'linux/arm64,linux/amd64'

when:
  - event: push
    branch: "flimmy_ci_tests"

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v1

steps:
  - name: get craftmaker
    image: opencloudeu/woodpecker-windows-git:v1
    commands:
      - bash -c "git clone --depth=1 https://invent.kde.org/kde/craftmaster.git `$$CI_WORKSPACE/woodpecker_craft/CraftMaster/CraftMaster"

  - name: ls
    image: opencloudeu/woodpecker-windows-python:v1
    entrypoint: ["powershell", "-noprofile", "-noninteractive", "-command", "$$IsWindows=$$true; [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($Env:CI_SCRIPT)) | iex"]
    commands:
      - New-Item -itemtype SymbolicLink -path $$HOME/craft -value $$env:CI_WORKSPACE/woodpecker_craft
      - New-Item -Path $$HOME/cache -ItemType Directory -ErrorAction SilentlyContinue
      - pwsh .github/workflows/.craft.ps1 --setup
      - pwsh .github/workflows/.craft.ps1 -c --unshelve .craft.shelf
      - pwsh .github/workflows/.craft.ps1 -c craft
      - New-Item -ItemType Directory binaries
      - pwsh .github/workflows/.craft.ps1 -c --set "forceAsserts$$($$env:CI_PIPELINE_EVENT -ne "tag")" opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c --set "srcDir=$$env:CI_WORKSPACE" opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c --set "buildNumber=$$env:CI_PIPELINE_NUMBER" opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c dev-utils/nsis
      - pwsh .github/workflows/.craft.ps1 -c --install-deps opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c --shelve .craft.shelf
      - Copy-Item .craft.shelf binaries/craft.shelf
      - pwsh .github/workflows/.craft.ps1 -c --no-cache opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c --no-cache --test opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c --no-cache --package opencloud/opencloud-desktop
      - pwsh .github/workflows/.craft.ps1 -c --no-cache --package --options "[Packager]PackageType=AppxPackager" --options "[Packager]Destination=$$env:CI_WORKSPACE/appx/" opencloud/opencloud-desktop
      - Copy-Item ${HOME}/craft/binaries/* binaries/
      - Copy-Item appx/* binaries/
      - dir binaries
      