---
variables:
  - &squish_image 'arturneumann/squish'
  - &minio_image 'minio/mc:RELEASE.2021-10-07T04-19-58Z'
  - &minio_environment
    AWS_ACCESS_KEY_ID:
      from_secret: cache_s3_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_s3_secret_key
    CACHE_BUCKET:
      from_secret: cache_s3_bucket
    MC_HOST:
      from_secret: cache_s3_server

steps:
  - name: fix-permissions
    image: owncloud/ubuntu:20.04
    commands:
      - chmod o+w /woodpecker/desktop/ -R
  - name: build-client-for-ui-tests
    image: *squish_image
    commands:
      - mkdir -p /woodpecker/desktop/build
      - cd /woodpecker/desktop/build
      - cmake %s -S .. -GNinja  -DCMAKE_BUILD_TYPE=Debug  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
      - ninja
  - name: upload-desktop-client-cache
    commands:
      - mc alias set s3 $MC_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -a -r /woodpecker/desktop/build/bin s3/$CACHE_BUCKET/desktop-build/${CI_COMMIT_SHA}/
      - mc ls --recursive s3/$CACHE_BUCKET/desktop-build
    environment:
      <<: *minio_environment
    image: *minio_image

when:
  - branch:
      - main
      - stable-*
    event:
      - push
      - manual
  - event: pull_request
  - event: tag
workspace:
  base: /woodpecker/
  path: desktop
