---
variables:
  - &MC_HOST "https://s3.ci.opencloud.eu"

when:
  - event: push
    branch: "flimmy_ci_tests"

matrix:
  include:
    - platform: linux/amd64
      clone_image: woodpeckerci/plugin-git
      build_image: ghcr.io/opencloud-eu/ci-docker-desktop/appimage:latest
      target: linux-gcc-x86_64
    - platform: windows/amd64
      clone_image: opencloudeu/woodpecker-windows-git-plugin:v2
      build_image: opencloudeu/woodpecker-windows-desktop-build-tools:v1
      target: windows-cl-msvc2022-x86_64

labels:
  platform: ${platform}
  backend: docker

clone:
  - name: clone
    image: ${clone_image}

steps:
  - name: build
    image: ${build_image}
    environment:
      CRAFT_TARGET: ${target}
    # entrypoint: [
    #   "pwsh",
    #   "-noprofile",
    #   "-noninteractive",
    #   "-command",
    #   "Set-StrictMode -Version Latest; `
    #   $ErrorActionPreference = 'Stop'; `
    #   $ProgressPreference = 'SilentlyContinue'; `
    #   $PSNativeCommandUseErrorActionPreference = $true; `
    #   echo $([System.Text.Encoding]::UTF8.GetString(`
    #   [System.Convert]::FromBase64String($Env:CI_SCRIPT)`
    #   )) | iex"]
    commands:
      - cd $$env:CI_WORKSPACE ; pwsh .woodpecker/build.ps1

  - name: uploadc
    image: woodpeckerci/plugin-s3
    settings:
      bucket:
        from_secret: cache_s3_bucket
      access_key:
        from_secret: cache_s3_access_key
      secret_key:
        from_secret: cache_s3_secret_key
      source: content.txt
      target: /$CI_REPO_NAME/$CI_PIPELINE_NUMBER
      endpoint: *MC_HOST
      path_style: true
