---
labels:
  platform: windows/amd64
  backend: docker

# variables:
#   - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
#   - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
#   - &publish_platforms 'linux/arm64,linux/amd64'

when:
  - event: push
    branch: "flimmy_ci_tests"

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v1

steps:
  - name: Craft setup
    image: opencloudeu/woodpecker-windows-python:v1
    commands:
      - dir
      - New-Variable -Name IsWindows -Value $$true
      - dir
      - New-Item -itemtype SymbolicLink -path $$HOME/craft -value $$env:CI_WORKSPACE/woodpecker_craft
      - New-Item -Path $$HOME/cache -ItemType Directory -ErrorAction SilentlyContinue
      - pwsh .github/workflows/.craft.ps1 --setup
