---
labels:
  platform: windows/amd64
  backend: docker

when:
  - branch:
      - main
      - stable-*
    event:
      - push
      - manual
  - event: pull_request
  - event: tag

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v2

steps:
  - name: Clone Craftmaster
    image: opencloudeu/woodpecker-windows-git:v2
    commands:
      - git clone --depth=1 https://invent.kde.org/kde/craftmaster.git `
        $$env:CI_WORKSPACE/woodpecker_craft/CraftMaster/CraftMaster

  - name: build
    image: opencloudeu/woodpecker-windows-desktop-build-tools:v1
    environment:
      CRAFT_TARGET: windows-cl-msvc2022-x86_64
      CRAFT_PACKAGE_SYMBOLS: true
    entrypoint: [
      "pwsh",
      "-noprofile",
      "-noninteractive",
      "-command",
      "Set-StrictMode -Version Latest; `
      $ErrorActionPreference = 'Stop'; `
      $ProgressPreference = 'SilentlyContinue'; `
      $PSNativeCommandUseErrorActionPreference = $true; `
      echo $([System.Text.Encoding]::UTF8.GetString(`
      [System.Convert]::FromBase64String($Env:CI_SCRIPT)`
      )) | iex"]
    commands:
      - cd $$env:CI_WORKSPACE ; .woodpecker/build.ps1
