---
labels:
  platform: windows/amd64
  backend: docker

# variables:
#   - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:latest'
#   - &publish_repos 'opencloudeu/wccs,quay.io/opencloudeu/wccs'
#   - &publish_platforms 'linux/arm64,linux/amd64'

when:
  - event: push
    branch: "flimmy_ci_tests"

clone:
  - name: clone
    image: opencloudeu/woodpecker-windows-git-plugin:v1

steps:
  - name: get craftmaker
    image: opencloudeu/woodpecker-windows-git:v1
    commands:
      - bash -c "git clone --depth=1 https://invent.kde.org/kde/craftmaster.git /woodpecker/src/craft/CraftMaster/CraftMaster"

  - name: ls
    image: opencloudeu/woodpecker-windows-python:v1
    commands:
      - '`$$IsWindows=`$$true'
      - .github/workflows/.craft.ps1 --setup
