variables:
  - &squish_image 'opencloudeu/squish@sha256:efaaa7749b9987dd3164288a55b2dc5514acd5eef01b0ec72f6b9b41d761378f'
  - &minio_image 'minio/mc:RELEASE.2021-10-07T04-19-58Z'
  - &minio_environment
    AWS_ACCESS_KEY_ID:
      from_secret: cache_s3_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: cache_s3_secret_key
    CACHE_BUCKET:
      from_secret: cache_s3_bucket
    MC_HOST: 'https://s3.ci.opencloud.eu'

when:
  - branch:
      - main
      - stable-*
    event:
      - push
      - manual
  - event: tag
  - event: pull_request
    evaluate: |
      !(CI_COMMIT_SOURCE_BRANCH matches "next-release/(main|stable-*)" && CI_COMMIT_AUTHOR == "openclouders")
  - event: cron
    cron: nightly*

workspace:
  base: /woodpecker/
  path: desktop

steps:
  - name: check-python-cache
    image: *minio_image
    environment:
      <<: *minio_environment
    commands:
      - mc alias set s3 $MC_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc ls s3/$CACHE_BUCKET/desktop-build
      - bash test/gui/woodpecker/script.sh check_python_cache

  - name: install-python-modules
    image: *squish_image
    environment:
      PYTHONUSERBASE: /woodpecker/desktop
    commands:
      - . ./.woodpecker.env
      - if $PYTHON_CACHE_FOUND; then exit 0; fi
      - make -C test/gui/ pip-install
      - python3.10 -m pip list -v
      - requirements_sha=$(sha1sum test/gui/requirements.txt | cut -d" " -f1)
      - tar -czvf /woodpecker/desktop/python-cache-$requirements_sha.tar.gz lib/python3.10/site-packages

  - name: upload-python-cache
    image: *minio_image
    environment:
      <<: *minio_environment
    commands:
      - . ./.woodpecker.env
      - if $PYTHON_CACHE_FOUND; then exit 0; fi
      - mc alias set s3 $MC_HOST $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -r -a /woodpecker/desktop/python-cache*.tar.gz s3/$CACHE_BUCKET/desktop-build/
      - mc ls s3/$CACHE_BUCKET/desktop-build
