when:
  event: push
  branch: stable-3.0

steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:latest
    settings:
      git_email: devops@opencloud.eu
      forge_type: github
      release_branch: stable-3.0,
      forge_token:
        from_secret: github_token
