[GeneralSettings]
# creating cache files on github makes no sense
Packager/CreateCache = False

Paths/CCACHE_DIR = ${Env:HOME}/ccache
Compile/UseCCache = True

Packager/AppxPublisherId = CN=44DA8A24-8237-46B0-B4A2-D297A6A22705
CodeSigning/Enabled = True
CodeSigning/CommonName = Test certificate for 'OpenCloud Desktop Client [OSS]'
CodeSigning/Organization =
CodeSigning/State =
CodeSigning/Country =
CodeSigning/WindowsCustomSignCommand = pwsh ${Env:GITHUB_WORKSPACE}/.github/workflows/.signpath.ps1 

[linux-gcc-x86_64]
Environment/SourceCommand = export PKG_CONFIG_PATH=(/usr/bin/pkg-config --variable pc_path pkg-config) && source /opt/rh/gcc-toolset-14/enable

[linux-gcc-x86_64-debug]
Environment/SourceCommand = export PKG_CONFIG_PATH=(/usr/bin/pkg-config --variable pc_path pkg-config) && source /opt/rh/gcc-toolset-14/enable
